export const universities = [
  // Azerbaijan Universities
  "ADA University",
  "Azerbaijan State Oil and Industry University",
  "Azerbaijan Technical University",
  "Azerbaijan University of Architecture and Construction",
  "Azerbaijan University of Languages",
  "Baku Engineering University",
  "Baku Higher Oil School",
  "Baku State University",
  "Khazar University",
  "Nakhchivan State University",
  "Western Caspian University",
  "Azerbaijan Medical University",
  "Azerbaijan State University of Economics",
  "Azerbaijan State Pedagogical University",
  "Azerbaijan University",
  "Baku Slavic University",
  "Ganja State University",
  "Mingachevir State University",
  "Sumgait State University",
  "Azerbaijan State Academy of Fine Arts",
  "Azerbaijan National Conservatory",
  "Academy of Public Administration",
  "Azerbaijan Diplomatic Academy",
  
  // Top US Universities
  "Massachusetts Institute of Technology (MIT)",
  "Stanford University",
  "Harvard University",
  "California Institute of Technology (Caltech)",
  "Princeton University",
  "Yale University",
  "Columbia University",
  "University of Chicago",
  "Duke University",
  "Northwestern University",
  "Johns Hopkins University",
  "Cornell University",
  "University of Pennsylvania",
  "Brown University",
  "Dartmouth College",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "University of Michigan",
  "New York University (NYU)",
  "Carnegie Mellon University",
  "University of Southern California",
  "University of Texas at Austin",
  "Georgia Institute of Technology",
  "University of Washington",
  "University of Wisconsin-Madison",
  "University of Illinois Urbana-Champaign",
  "Boston University",
  "University of Virginia",
  "University of North Carolina at Chapel Hill",
  "Ohio State University",
  "Pennsylvania State University",
  "Purdue University",
  "University of Florida",
  "University of Maryland",
  "Arizona State University",
  "Indiana University",
  "University of Minnesota",
  "University of Colorado Boulder",
  "University of Arizona",
  
  // Top UK Universities
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "London School of Economics (LSE)",
  "University of Edinburgh",
  "King's College London",
  "University of Manchester",
  "University of Bristol",
  "University of Warwick",
  "University of Glasgow",
  "Durham University",
  "University of Sheffield",
  "University of Birmingham",
  "University of Leeds",
  "University of Southampton",
  "University of Nottingham",
  "Queen Mary University of London",
  "Lancaster University",
  "University of York",
  "University of Exeter",
  "Cardiff University",
  "University of Bath",
  "University of Liverpool",
  "Newcastle University",
  
  // Top European Universities
  "ETH Zurich",
  "EPFL (Swiss Federal Institute of Technology Lausanne)",
  "University of Zurich",
  "Ludwig Maximilian University of Munich",
  "Technical University of Munich",
  "Heidelberg University",
  "Humboldt University of Berlin",
  "Free University of Berlin",
  "University of Amsterdam",
  "Delft University of Technology",
  "KU Leuven",
  "Sorbonne University",
  "Paris Sciences et Lettres (PSL)",
  "École Polytechnique",
  "École Normale Supérieure",
  "University of Copenhagen",
  "Uppsala University",
  "Karolinska Institute",
  "University of Helsinki",
  "University of Oslo",
  "Trinity College Dublin",
  "University of Vienna",
  "University of Barcelona",
  "Complutense University of Madrid",
  "University of Milan",
  "Sapienza University of Rome",
  "University of Bologna",
  "Leiden University",
  "Utrecht University",
  "Technical University of Denmark",
  "University of Groningen",
  "Erasmus University Rotterdam",
  "Wageningen University",
  "University of Geneva",
  "University of Basel",
  
  // Top Asian Universities
  "National University of Singapore (NUS)",
  "Nanyang Technological University",
  "Tsinghua University",
  "Peking University",
  "University of Hong Kong",
  "Chinese University of Hong Kong",
  "Hong Kong University of Science and Technology",
  "University of Tokyo",
  "Kyoto University",
  "Tokyo Institute of Technology",
  "Osaka University",
  "Seoul National University",
  "KAIST",
  "Yonsei University",
  "Korea University",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Science",
  "National Taiwan University",
  "Fudan University",
  "Shanghai Jiao Tong University",
  "Zhejiang University",
  "Nanjing University",
  "University of Science and Technology of China",
  
  // Top Australian/NZ Universities
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "University of Queensland",
  "University of New South Wales",
  "Monash University",
  "University of Western Australia",
  "University of Adelaide",
  "University of Auckland",
  "University of Otago",
  
  // Top Canadian Universities
  "University of Toronto",
  "McGill University",
  "University of British Columbia",
  "University of Alberta",
  "University of Waterloo",
  "University of Montreal",
  "McMaster University",
  "University of Calgary",
  "Queen's University",
  "Western University",
  "University of Ottawa",
  "Simon Fraser University",
  "Dalhousie University",
  "University of Victoria",
  
  // Middle East Universities
  "King Abdullah University of Science and Technology",
  "American University of Beirut",
  "American University in Cairo",
  "Tel Aviv University",
  "Hebrew University of Jerusalem",
  "Technion - Israel Institute of Technology",
  "Weizmann Institute of Science",
  "King Fahd University of Petroleum and Minerals",
  "King Saud University",
  "Qatar University",
  "United Arab Emirates University",
  "Khalifa University",
  "Sharjah University",
  "American University of Sharjah",
  "Istanbul Technical University",
  "Boğaziçi University",
  "Middle East Technical University",
  "Koç University",
  "Sabancı University",
  "Bilkent University",
  "Tehran University",
  
  // African Universities
  "University of Cape Town",
  "University of the Witwatersrand",
  "Stellenbosch University",
  "University of Pretoria",
  "Cairo University",
  "University of Nairobi",
  "University of Ghana",
  "University of Lagos",
  "University of Ibadan",
  "Makerere University",
  
  // Latin American Universities
  "University of São Paulo",
  "University of Campinas",
  "National Autonomous University of Mexico",
  "Monterrey Institute of Technology",
  "Pontifical Catholic University of Chile",
  "University of Chile",
  "University of Buenos Aires",
  "University of the Andes (Colombia)",
  "Pontifical Catholic University of Peru",
  
  // Russia/CIS Universities
  "Moscow State University",
  "Saint Petersburg State University",
  "Moscow Institute of Physics and Technology",
  "Novosibirsk State University",
  "Higher School of Economics",
  "ITMO University",
  "Bauman Moscow State Technical University",
  "Nazarbayev University",
  "Al-Farabi Kazakh National University",
  
  // Research Institutions
  "Max Planck Institutes",
  "CERN",
  "NASA",
  "National Institutes of Health (NIH)",
  "Los Alamos National Laboratory",
  "Lawrence Berkeley National Laboratory",
  "Brookhaven National Laboratory",
  "Oak Ridge National Laboratory",
  "Sandia National Laboratories",
  "Fraunhofer Society",
  "CNRS (French National Centre for Scientific Research)",
  "Chinese Academy of Sciences",
  "Russian Academy of Sciences",
  
  // Medical Schools / Teaching Hospitals
  "Mayo Clinic",
  "Cleveland Clinic",
  "Massachusetts General Hospital",
  "Johns Hopkins Hospital",
  "UCSF Medical Center",
  "Charité - Universitätsmedizin Berlin",
  
  // Other option for unlisted institutions
  "Other (please specify in bio)"
].sort((a, b) => {
  // Keep "Other" at the end
  if (a.includes("Other")) return 1;
  if (b.includes("Other")) return -1;
  return a.localeCompare(b);
});
